version: '2'

services:
  app:
    image: 'recipes-engine:latest'
    build:
      context: .
    container_name: recipes-engine
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/{DB_NAME}
      - SPRING_DATASOURCE_USERNAME={DB_USER}
      - SPRING_DATASOURCE_PASSWORD={DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8989:8989'

  db:
    image: 'postgres:15-alpine'
    container_name: db
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}